### ISSUE TITLE
Trouble with using a custom nav-section with collapsable headers

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#107]
While working on adding a collapsable custom nav slot, there is an issue with the active slot indicator (the white bar that displays on the left side of whatever section you have clicked).  I have a sandbox spun up with a working example of what we are experiencing ([sandbox link](https://codesandbox.io/s/sad-shadow-ju9u07)).  

What you will see is that if you click on the `Authentication` tab which is a standard tab the white bar moves to the tab as expected.  Then if you click on the `Getting Started` tab which is a custom nav slot it also moves the white bar to the tab as expected.  However, if you click back on the `Authentication` tab it now leaves the bar next to both the `Getting Started` AND the `Authentication` tab.  We did some debugging through the code and it seems to have something to do with lines 756-789 in the `openapi-explorer.js`.

**Comment by wparad** [comment]
Hey, having trouble loading the sandbox from the link provided:
https://codesandbox.io/s/sad-shadow-ju9u07 => 
![image](https://user-images.githubusercontent.com/5056218/192612008-b32efab0-8be2-4de5-9a21-ca72008540d3.png)

You might be able to investigate a bit further, if possible. These lines:
```js

**Comment by silverbullettruck2001** [comment]
@wparad I forgot to mention that you need to navigate to [https://codesandbox.io/s/sad-shadow-ju9u07/develop/test](https://codesandbox.io/s/sad-shadow-ju9u07/develop/test) to get the sandbox to respond correctly.

**Comment by wparad** [comment]
That doesn't work either:
![image](https://user-images.githubusercontent.com/5056218/192627564-bc4ff71a-e5d6-4ac2-9743-374305fada73.png)

There's a lot going on in that sandbox, I think I'm going to request getting a minimal spec here. I need the openapi spec and the html slots being filled, anything more complex than that is going to be a huge ask to track if there really is a problem.

**Comment by silverbullettruck2001** [comment]
@wparad Please try once more.  What I have in the sandbox is as minimal as I can provide.  You just need to go to `https://codesandbox.io/s/sad-shadow-ju9u07` to get to the sandbox, then once it is loaded, in the test browser add `/develop/test` as you can see in the provided screenshot.  You will also notice that I have to use `0.10.426` because something with the new `computedUrl` doesn't seem to work in the `0.10.428` release.  I was going to submit a ticket, but wanted to deal with this first.

![image](https://user-images.githubusercontent.com/26559157/192637691-889cdee9-06de-4367-bb6d-2988bd4435f1.png)

**Comment by wparad** [comment]
There's a problem with your code in how you are deciding when to add and remove `borderLeft`, sometimes clicking your custom elements works and other times it doesn't.

For starters the issue with the border showing is because of this class:
https://codesandbox.io/s/sad-shadow-ju9u07?file=/src/index.css:598-630

and when it is incorrectly applied to your custom nav sections. I suggest removing this class or at least the border left from the css, and then click around, you'll see then the border gets correctly added to the custom nav sections.

You can specifically see when I do this and then **click very carefully outside of your custom nav elements** that the border is correctly applied. Only when clicking into your custom functionality does it do the wrong thing and not apply the border. The logic therefore must be incorrect in your custom handling.

I'm not sure what else we could do here, if we're missing an event to make this easier we can try to add something, but at this point it just seems like a bug in the code for this component, and therefore outside of the scope of what we can investigate to support.

I think that we've successfully narrowed down the problem to that logic, so I'm going to close this ticket.

![Peek 2022-09-27 23-40](https://user-images.githubusercontent.com/5056218/192640962-ce180c28-4cbf-416a-9fd7-3a35c3d6d0de.gif)

**Comment by jmcpeak** [comment]
Easiest way to repro - add this as the only custom code

`<div slot="nav-section"><h4>New Nav Section</h4></div>`

If you click the actual h4 text, the currently selected nav item will _not_ be cleared.
If you click the area to the right of the text, it works as expected.

It has to do with the logic around event bubbling and how you find the selected index here:

`const repeatedElementIndex = assignedNodes && [].findIndex.call(assignedNodes, (slot) => slot === event.target);`

**Comment by wparad** [comment]
@jmcpeak that's for pointing this out, I'm going to reopen this issue based on that, it seems like we need to do a better job detecting the correct parent element node to be passing around
