### ISSUE TITLE
Fill in example parameters instead of using placeholders

### ISSUE THREAD

**Issue by misaugstad** [Rhosys/openapi-explorer#113]
Example parameters should probably be filled in using the HTML `value` property instead of the `placeholder` property. If someone wants to try out the query with parameters that are not the example ones, then it would be easy for them to delete the example values that are there. But if someone just wants to try out the provided example, they now have to type in the example values themselves, which is more difficult.

My use case is that the parameters for my API are latitude and longitude values. Users generally don't have lat/lngs that they're trying to input when trying out the API. They will likely want to use the defaults, so it would be really nice to have the text auto-filled for them!

![Screenshot from 2022-11-29 15-03-59](https://user-images.githubusercontent.com/6518824/204667645-746ed80f-ee9a-42bc-939d-d44f6a28b667.png)

**Comment by wparad** [comment]
defaults are fillled by default, examples are only placeholders. Does that explain what you are seeing currently?

**Comment by misaugstad** [comment]
Ah yes, I forgot to mention the defaults! I'm suggesting that we start by filling with defaults. If there is no default value, then fill with an example value (instead of it being only a placeholder).

**Comment by wparad** [comment]
Examples are examples so it doesn't make sense as a standard to pre-populate these since people will actually use the API. What actually happens is a really bad user experience of having to delete these values every time. And worse, if they forget to delete one it goes to the api like that.

So this won't be changed. That being said, you can automatically fill these in yourself with a small bit of code:
```html
<openapi-explorer @spec-loaded="onSpecLoaded"> </openapi-explorer>
```

For example populate the user's id into default property to be automatically used:
```js
onSpecLoaded(data) {
  data.detail.tags.forEach(tag => {
    tag.paths.filter(path => path.parameters).forEach(path => {
      path.parameters.forEach(p => {
        p.schema.default ??= p.schema.example;
      });
    });
  });
}
```
