### ISSUE TITLE
Styling options for method types?

### ISSUE THREAD

**Issue by gitblit** [Rhosys/openapi-explorer#130]
I prefer the presentation option of the method & route but I miss style differentiation on verbs. It appears that in "desktop" sizes there are no special css classes applied to the verbs and thus they can't be styled so easily. I do note that in responsive, there is a very nice styled-verb presentation.

Any possibility of improving this?

<img width="147" alt="image" src="https://user-images.githubusercontent.com/868217/218289380-7cdb7f5a-e3bf-4af8-8e87-559a5b8b7d55.png">

<img width="189" alt="image" src="https://user-images.githubusercontent.com/868217/218289476-140a341c-dac0-41b3-b52b-01d49c614305.png">

**Comment by wparad** [comment]
Seems like a great idea, I'm not sure what's a good starting implementation. Want to try working something out and we can see if we can get that in. Since you are the first one here, we don't even need the css parts variable, we can directly use your desired css, as long as it isn't something so ridiculous :)

**Comment by gitblit** [comment]
Thanks for the change! Will you release a new package soon with this & #136 ?

**Comment by wparad** [comment]
Everything that gets merged gets automatically released.
