### ISSUE TITLE
Is it possible to control the indentation config for Prism?

### ISSUE THREAD

**Issue by gitblit** [Rhosys/openapi-explorer#138]
Are there any exposed options to configure Prism? I'd definitely like to be able to control the indentation. We typically use 2 spaces.

**Comment by wparad** [comment]
Probably not, but which specific prism usage are we talking about?

**Comment by gitblit** [comment]
Lol. When I thought about this request this morning prior to seeing your reply, I realized I didn't pinpoint _where_ in my question. The JSON response output from an executed request.

**Comment by wparad** [comment]
Okay, that actually isn't prism, that's the library. We are using `8` spaces for the display, and we aren't going to change that. We could muck around how we display it, but that's really a different conversation.

What I really think you want is when you copy part of the text or when click the `Copy` button, that text should only be 2 spaces, am I right?

We can definitely change the copy button so that it only outputs 2 spaces, the fact when you hit copy it has 8 spaces, does very much feel wrong.

**Comment by gitblit** [comment]
Actually, I did mean the UI/display spacing not the copy spacing. Maybe there could be an integer property to define it, but I am not going to cry if it remains a hard-coded `8`; the library is too good!

**Comment by wparad** [comment]
> Actually, I did mean the UI/display spacing not the copy spacing. Maybe there could be an integer property to define it, but I am not going to cry if it remains a hard-coded `8`; the library is too good!

The display is going to be optimized to be visible and have good accessibility, at `2` spaces, it very difficult to read. Also what even is two spaces?

Every browser defines the width of a space differently, also the font family impacts that as well. If it really is only about how it looks, and it isn't about functionality, then I would be tempted to close this...HOWEVER, I really do think there is a bug with the copy button, because irrespective of how we choose to display the content, what you copy out should definitely always be usable. 8 spaces in the resultant copy to clipboard is incorrect.
