### ISSUE TITLE
Can't get OAuth2 flow to work

### ISSUE THREAD

**Issue by max-mathieu** [Rhosys/openapi-explorer#41]
Swagger UI provides a html file (https://github.com/swagger-api/swagger-ui/blob/cc408812fc927e265da158bf68239530740ab4cc/dist/oauth2-redirect.html) as redirect URL of an OAuth2 flow, but it looks like `openapi-explorer` needs an undocumented `oauth-redirect-url` param

Could this be generated as a dist file and do whatever `postMessage` magic is expected?

(also, a nice addition would be to allow passing the OAuth2 client-id as a param for hosted docs)

**Comment by wparad** [comment]
I can definitely be this doesn't work as it is supposed to, we shouldn't need any `postMessage` magic, but I can definitely see that it would help to have a generated file like the swagger-ui one. I can also see the need to have the client_id for oauth, let me take a good look at what is happening here and see what we can do.

**Comment by wparad** [comment]
Okay, so some changes in version `0.7` now there is a method to set the `clientId`, `setAuthenticationConfiguration('authName', { clientId })`, which will populate the `Authentication` screen in the explorer. Clicking on the `GET TOKEN` button will lead the user through the flow. If for some reason the redirect location needs to be specified there are additional instructions in the [repository oauth configuration documentation](https://github.com/Rhosys/openapi-explorer/blob/release/0.7/docs/documentation.md#oauth-configuration)

I'm going to close this issue for now, but if there are any issues we can reopen it, I fully expect depending on the AS you are using, we might need to make some adjustements.

**Comment by max-mathieu** [comment]
Fantastic work @wparad !! Let me test this out :) We're using Auth0 so they do support PKCE and all, but will report any issue. In case I face issues, do you prefer that I reopen this issue, or create a new one?

2 minor comments in the meantime, hoping I'm reading/doing the code correctly:
- IIUC, the `authorizationCode` flow may need a secret (though in single-page apps and native apps they recommend having an empty secret and PKCE). Seems like https://github.com/Rhosys/openapi-explorer/blob/127150e21a5c13ff6ee332b1c816e49e9866e262/src/templates/security-scheme-template.js#L270 used to include it, but now I'm getting only the client ID
- setting the client id worked great for me, though I believe the `securityObj.redirectUri` only defaults to the current page if there's an explicit call to `setAuthenticationConfiguration`. If you don't call `setAuthenticationConfiguration` and manually enter a client id, it triggers an error on https://github.com/Rhosys/openapi-explorer/blob/127150e21a5c13ff6ee332b1c816e49e9866e262/src/templates/security-scheme-template.js#L173

Hope this helps :)

**Comment by wparad** [comment]
Thanks for the bug report on defaulting the redirect_uri, in most cases this isn't going to work due to the restrictions a lot of providers put on the format of this url, but it isn't bad to have a sane default.

Regarding the secret, we want to avoid bad security practices, which would include putting client secrets anywhere other than source code. If someone runs across this and wants to use a secret, they can always point the token url at the same location in the service api which accepts token exchanges. Usually for more complex apps, this exchange isn't happening through the OpenAPI Explorer anyway, so it is a moot point.

I could see hypothetically the one use case, might be for a platform that provides client/secrets to its users and wants to use the explorer to allow their customers a DX to let them test those clients with the platform. Again we want to dissuade vulnerable and poor security practices, would recommend potentially adding additional "event triggers" that a UI could do something custom before calling some service API. But unless that is a real concern for you/your users, I want to avoid discussing it here :)

If you run into related issues, tracking that problem here is better for posterity. If it is only somewhat related, a separate issue is probably better.

**Comment by wparad** [comment]
For what it's worth, we run an authorization platform that integrates with all OAuth providers (I believe Auth0 is one of them), and one of biggest opportunities we have is to prevent these poor practices. I wouldn't be surprised in near future implicit and client credentials grants are removed from here, and replaced with push authentication requests, which the cutting edge security providers already support.

I'm hesitant to remove features that teams are using, especially when it could be being consumed as a developer interacting with an API they don't control (i.e. using this isn't of postman). But it allows for potential vulnerabilities if done incorrectly, so there are huge tradeoffs.
