### ISSUE TITLE
Collapsed/Expanded Operations Default Setting

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#65]
Make it so you can specify if you want to have the `Operations` section loaded so that they are all collapsed by default or expanded by default? Right now it defaults to expanded, but it would be nice to be able to have that customizable, especially now with the recent changes to how expanded and collapse works.

**Comment by wparad** [comment]
Now you should be able to add `collapse` to the `<openapi-explorer collapse></openapi-exprorer>` to control the default state of the operations.

**Comment by silverbullettruck2001** [comment]
@wparad, your changelog looks like you removed the ability to use the `show-components` property, but I use it and set it to `false`.  I forgot to remove it and it still worked.  I am hoping that you accidentally removed it as I appreciate the ability to not display the components.

**Comment by wparad** [comment]
That's because it isn't a documented feature. Non-documented features should not be in our changelog, that was a mistake. The list of documented features is: https://github.com/Rhosys/openapi-explorer/blob/release/0.9/docs/documentation.md#documentation

If this is a request to make it a permanent feature, we would appreciate a separate issue. Thanks!

**Comment by silverbullettruck2001** [comment]
Thanks, I will get that issue added.  Also, I noticed that the `collapse` is not collapsing the `components` when I have it set:

![image](https://user-images.githubusercontent.com/26559157/181484414-c2853cb8-68b1-4652-bac3-6b03229e05ba.png)

**Comment by wparad** [comment]
It seems `components` collapsing was never completely implemented...
