### ISSUE TITLE
Embed Version

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#67]
Could you add a way to include the version of `openapi-explorer` as a non-displayable element on the page so there is a way to verify versions without making it obtrusive?  I know as users we could add this in ourselves and bump it every time we upgrade, but it would be nice to have it done natively and automatically as part of the component.

**Comment by wparad** [comment]
You can load the version of a package by by referencing the package.json file. The version is in there.

What are hoping to accomplish with having something like this?

**Comment by silverbullettruck2001** [comment]
Just to be able to verify what version of the component is deployed.  Like how most applications have a way of going to `Help-->About` to display the version number or how most web apps have small text at the bottom of their `Settings` page that lists the version number.  Something similar is what I was looking for to give a sanity check.

**Comment by wparad** [comment]
Could you tell me about how you are hosting the component? I would expect that you could easily

```js
import { version } from 'openapi-explorer/package.json';
console.log('OpenAPI Explorer version:', version);`
```

Or at that point you can embed it whereever you would like. This is also way more flexible then having a DOM component which would need reflection, if you wanted to do anything clever.

I want to avoid adding non-functional features, it's hard to ensure that they will always work and won't break in the future. They also tend to be abused because it isn't clear their intended purpose.

Assuming that works, I'm going to close this issue.
